name: Deploy to Kubernetes
description: Deploys an image to kubernetes
inputs:
  deployment_file:
    description: The name of the kubernetes deployment file to apply
    required: true
    default: k8s.dev.yml
  deployment_name:
    description: The name of the deployment to verify / deploy
    required: true
  namespace:
    description: The kubernetes namespace
    required: true
    default: dev
  do_kubernetes_cluster_name:
    description: The name of the k8s cluster in kubernetes
    required: true
  do_token:
    description: The digital ocean token to authenticate with the DO API
    required: true
  kubernetes_request_timeout:
    description: The timeout to pass to kubernetes when issuing the deploy / verification commands
    required: false
    default: "300s"

runs:
  using: composite
  steps:
    - name: Install Digital Ocean CTL
      # Commit sha for top of V2
      uses: digitalocean/action-doctl@0e7c88a2988e3a39f018289c5a1b90d460a62ffc
      with:
        token: ${{inputs.do_token}}
    
    - name: Configure Kubernetes
      shell: bash
      run: |
        doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{inputs.do_kubernetes_cluster_name}}

    - name: Deploy to K8s
      shell: bash
      run: |
        kubectl --namespace=${{ inputs.namespace }} apply -f ${{ inputs.deployment_file }} --request-timeout='${{ inputs.kubernetes_request_timeout }}'

    - name: Verify Deployment
      shell: bash
      run: |
        kubectl --namespace=${{ inputs.namespace }} rollout status deployment/${{ inputs.deployment_name }} --request-timeout='${{ inputs.kubernetes_request_timeout }}'
